<a href="https://colab.research.google.com/github/Basteen-A/CALCULATE-MEAN-MEDIAN-VARIANCE-AND-STANDARD-DEVIATION-Using-PANDAS/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#(#)Converting Arrays to NumPy Arrays

In [2]:
import numpy as np
arr = [1,2,3]
np.array(arr)

nested_arr = [[1,2],[3,4],[5,6]]
np.array(nested_arr)

array([[1, 2],
       [3, 4],
       [5, 6]])

## NumPy Arrange Function: n-dimensional arrays


In [4]:
print(np.zeros((4,5)))
print(np.ones((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


NumPy Linspace Function

In [5]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


**# Random Number Generation:**

Generate random numbers in a uniform distribution

In [6]:
print(np.random.rand(10))
print(np.random.rand(3,4))

[0.39347484 0.26071448 0.16178229 0.03987777 0.39127683 0.83547048
 0.56037727 0.0079339  0.20660905 0.28588765]
[[0.35925384 0.02774475 0.39822094 0.38287111]
 [0.27416496 0.81053202 0.09564286 0.08992558]
 [0.50351371 0.89749714 0.63925674 0.38705551]]


*# Array Computations*

In [7]:
new_arr = np.arange(1,11)
print(new_arr)
#Addition
print(new_arr + 5)
#Subtraction
print(new_arr - 5)
#Array Addition
print(new_arr + new_arr)
#Array Division
print(new_arr / new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**PANDAS**

*DataFrames*

In [10]:
import pandas as pd
data = {
"calories": [420, 380, 390],

"duration": [50, 40, 45]}
#load data into a DataFrame object:

df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


**# Pandas Read CSV**

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/22CAP05-MLL Datasets/1.PANDAS/data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


**# Pandas - Removing Duplicates**

In [3]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...  
164    False
165    False
166    False
167    False
168    False
Length: 169, dtype: bool


**# Pandas - Data Correlations**

In [4]:
print(df.corr())

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922721
Pulse    -0.155408  1.000000  0.786535  0.025120
Maxpulse  0.009403  0.786535  1.000000  0.203814
Calories  0.922721  0.025120  0.203814  1.000000


**# Pandas - Plotting**

*#Three lines to make our compiler able to draw:*

In [11]:
import sys
import matplotlib
matplotlib.use('Agg')
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df["Duration"].plot(kind = 'hist')
plt.show()
plt.savefig('myplot.png')